export enum Region {
  AndhraPradesh = 'andhraPradesh',
  ArunachalPradesh = 'arunachalPradesh',
  Assam = 'assam',
  Bihar = 'bihar',
  Chhattisgarh = 'chhattisgarh',
  Goa = 'goa',
  Gujarat = 'gujarat',
  Haryana = 'haryana',
  HimachalPradesh = 'himachalPradesh',
  Jharkhand = 'jharkhand',
  Karnataka = 'karnataka',
  Kerala = 'kerala',
  MadhyaPradesh = 'madhyaPradesh',
  Maharashtra = 'maharashtra',
  Manipur = 'manipur',
  Meghalaya = 'meghalaya',
  Mizoram = 'mizoram',
  Nagaland = 'nagaland',
  Odisha = 'odisha',
  Punjab = 'punjab',
  Rajasthan = 'rajasthan',
  Sikkim = 'sikkim',
  TamilNadu = 'tamilNadu',
  Telangana = 'telangana',
  Tripura = 'tripura',
  UttarPradesh = 'uttarPradesh',
  Uttarakhand = 'uttarakhand',
  WestBengal = 'westBengal',
  JammuKashmir = 'jammuKashmir',
  Ladakh = 'ladakh',
}

export enum Title {
  Mr = 'Mr',
  Mrs = 'Mrs',
  Ms = 'Ms',
  Dr = 'Dr',
  Prof = 'Prof',
}